"use client";

import { useEffect, useState } from "react";

type Quote = { listing_id: string; listing_name?: string; effective_monthly_cost?: number; first_quoted_effective?: number; final_quoted_effective?: number; risk_flag?: string; fraud_signals?: string[]; call_outcome?: { status?: string }; transcript_url?: string; recording_url?: string };
type Report = { ranked: Quote[]; recommendation?: { headline?: string }; benchmark?: { effective_monthly?: number; source?: string; sample_size?: number } };
const money = (value?: number) => value == null ? "—" : new Intl.NumberFormat("en-IN", { style: "currency", currency: "INR", maximumFractionDigits: 0 }).format(value);

export default function RealEstateReportPage() {
  const [report, setReport] = useState<Report | null>(null); const [error, setError] = useState<string | null>(null);
  useEffect(() => { const id = localStorage.getItem("scout_real_estate_requirement_id") ?? localStorage.getItem("scout_requirement_id"); if (!id) { setError("Confirm a property brief and complete a consented test call to see a report."); return; } void fetch(`/api/orchestrator/requirements/${id}/report`, { cache: "no-store" }).then(async (response) => { const body = await response.json(); if (!response.ok) throw new Error(body.error ?? "Could not load report."); setReport(body); }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Could not load report.")); }, []);
  return <div className="space-y-6"><header><p className="mono text-[11px] uppercase tracking-[0.18em] text-rust">Real estate · evidence-backed choice</p><h1 className="mt-2 text-3xl">Property negotiation report.</h1><p className="mt-2 text-sm text-charcoal/70">Scout compares effective monthly cost, moves high-risk offers out of the top position, and keeps evidence attached.</p></header><div className="wire" />{error && <p className="mono text-[11px] text-rust">{error}</p>}{report && <><section className="card p-5"><p className="mono text-[10px] uppercase text-charcoal/50">Scout recommendation</p><p className="mt-2 text-lg">{report.recommendation?.headline ?? "No property quotes yet."}</p>{report.benchmark?.effective_monthly != null && <p className="mono mt-3 text-[11px] text-charcoal/55">Market reference: {money(report.benchmark.effective_monthly)} · {report.benchmark.source ?? "unknown source"} · {report.benchmark.sample_size ?? 0} sources</p>}</section><ol className="card divide-y divide-line">{!report.ranked.length && <li className="p-6 text-sm text-charcoal/60">No itemized property quote has been recorded. Use a simulation or a consented test call first.</li>}{report.ranked.map((quote, index) => <li key={quote.listing_id} className="grid gap-3 p-5 sm:grid-cols-[44px_1fr_auto]"><span className="call-idx">{String(index + 1).padStart(2, "0")}</span><div><p className="font-medium">{quote.listing_name ?? quote.listing_id}</p><p className="mono mt-1 text-[11px] text-charcoal/55">{quote.call_outcome?.status?.replace(/_/g, " ") ?? "quote pending"} · {quote.risk_flag ?? "unassessed"}</p>{quote.fraud_signals?.length ? <p className="mono mt-2 text-[11px] text-rust">{quote.fraud_signals.join(" · ")}</p> : null}<div className="mt-2 flex gap-3 text-xs">{quote.transcript_url && <a className="underline" href={quote.transcript_url} target="_blank" rel="noreferrer">Transcript</a>}{quote.recording_url && <a className="underline" href={quote.recording_url} target="_blank" rel="noreferrer">Recording</a>}</div></div><div className="sm:text-right"><p className="mono text-[10px] uppercase text-charcoal/50">Effective monthly</p><p className="mt-1 text-lg">{money(quote.effective_monthly_cost)}</p>{quote.first_quoted_effective != null && quote.final_quoted_effective != null && quote.first_quoted_effective !== quote.final_quoted_effective && <p className="mono mt-1 text-[11px] text-sage">{money(quote.first_quoted_effective)} → {money(quote.final_quoted_effective)}</p>}</div></li>)}</ol></>}</div>;
}
