"use client";
import { useState } from "react";
const INPUT = "w-full rounded-md border border-line bg-white px-3 py-2 text-sm text-ink";
export default function RenovationPage() {
  const [form, setForm] = useState({ area: "", city: "", project_type: "painting", scope: "", finish_level: "standard", timeline: "", ideal: 80000, ceiling: 100000, posture: "balanced", site_visit: true, constraints: "" }); const [status, setStatus] = useState("");
  const ready = form.area && form.city && form.scope && form.ideal > 0 && form.ceiling >= form.ideal;
  async function submit() { if (!ready) return; setStatus("Saving contractor project brief…"); const spec = { vertical: "home_renovation", location: { area: form.area, city: form.city }, project_type: form.project_type, scope: form.scope, finish_level: form.finish_level, timeline: form.timeline, site_visit: form.site_visit, budget: { ideal: form.ideal, ceiling: form.ceiling, currency: "INR" }, negotiation_posture: form.posture, constraints: form.constraints.split(",").map((x) => x.trim()).filter(Boolean) }; try { const r = await fetch("/api/orchestrator/requirements", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ spec, source_path: "renovation_form" }) }); const record = await r.json(); if (!r.ok) throw new Error(record.error); await fetch(`/api/orchestrator/requirements/${record.id}/confirm`, { method: "POST" }); localStorage.setItem("scout_renovation_requirement_id", record.id); localStorage.setItem("scout_requirement_id", record.id); setStatus("Confirmed. Research contractor contacts next; outbound calls remain consented-test only."); } catch (e) { setStatus(e instanceof Error ? e.message : "Could not save project brief."); } }
  return <div className="space-y-6"><header><p className="mono text-[11px] uppercase tracking-[.18em] text-rust">Home renovation · project brief</p><h1 className="mt-2 text-4xl">Get comparable contractor quotes.</h1><p className="mt-2 text-sm text-charcoal/70">Scout standardizes scope, materials, warranty, timeline, and binding project total before it negotiates.</p></header><section className="card grid gap-4 p-5 sm:grid-cols-2"><Field label="Locality"><input className={INPUT} value={form.area} onChange={(e) => setForm({ ...form, area: e.target.value })} /></Field><Field label="City"><input className={INPUT} value={form.city} onChange={(e) => setForm({ ...form, city: e.target.value })} /></Field><Field label="Project"><select className={INPUT} value={form.project_type} onChange={(e) => setForm({ ...form, project_type: e.target.value })}>{["painting", "waterproofing", "tiling", "modular_kitchen", "renovation"].map((x) => <option key={x}>{x.replace(/_/g, " ")}</option>)}</select></Field><Field label="Finish level"><select className={INPUT} value={form.finish_level} onChange={(e) => setForm({ ...form, finish_level: e.target.value })}>{["basic", "standard", "premium"].map((x) => <option key={x}>{x}</option>)}</select></Field><Field label="Project scope"><textarea className={INPUT} value={form.scope} onChange={(e) => setForm({ ...form, scope: e.target.value })} placeholder="Rooms, dimensions, surface condition, materials…" /></Field><Field label="Timeline"><input className={INPUT} value={form.timeline} onChange={(e) => setForm({ ...form, timeline: e.target.value })} placeholder="e.g. finish before 15 August" /></Field><Field label="Ideal project total"><input type="number" className={INPUT} value={form.ideal} onChange={(e) => setForm({ ...form, ideal: Number(e.target.value) })} /></Field><Field label="Hard ceiling"><input type="number" className={INPUT} value={form.ceiling} onChange={(e) => setForm({ ...form, ceiling: Number(e.target.value) })} /></Field></section><button className="btn" disabled={!ready} onClick={() => void submit()}>CONFIRM CONTRACTOR BRIEF →</button><a className="btn-ghost ml-3" href="/discover">FIND CONTRACTORS →</a>{status && <p className="mono text-[11px] text-charcoal/65">{status}</p>}</div>;
}
function Field({ label, children }: { label: string; children: React.ReactNode }) { return <label className="grid gap-1.5"><span className="mono text-[10px] uppercase text-charcoal/55">{label}</span>{children}</label>; }
